import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

// Good to know: You should not manually add <head> tags such as <title> and <meta> to root layouts.
//  Instead, you should use the Metadata API which automatically handles advanced requirements 
//  such as streaming and de-duplicating <head> elements.
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


// Root layout, 
// just its have <html> and <body> tag. Any children layout dont have it 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <h1> Logo</h1>
          <ul>
            <li>
              <a href="/about">About</a>
            </li>
          </ul>
          <ul>
            <li>
              <a href="#">Sign Up</a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
