import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { MonteCarlo } from 'next/font/google'

const montecarlo = MonteCarlo({
  weight: '400',
  subsets: ["latin"]
})

const inter = Inter({ subsets: ['latin'] })

// Good to know: You should not manually add <head> tags such as <title> and <meta> to root layouts.
//  Instead, you should use the Metadata API which automatically handles advanced requirements 
//  such as streaming and de-duplicating <head> elements.
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


// Root layout, 
// just its have <html> and <body> tag. Any children layout dont have it 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"  >
      <body className={montecarlo.className}>
        <nav className='nav-bar'>
          <div className='left-side' >
            <h1> Logo</h1>
          </div>
          <div className='right-side'>
            <ul>
              <li>
                <a href="/about">About</a>
              </li>
              <li>
                <a href="#">Sign Up</a>
              </li>
            </ul>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
